### ISSUE TITLE
Version 2.2.0 release of `amazon/dynamodb-local` breaks parallel scan

### ISSUE THREAD

**Issue by tomwwright** [awslabs/amazon-dynamodb-local-samples#12]
I have some integration tests using parallel scan using [amazon/dynamodb-local:latest](https://hub.docker.com/r/amazon/dynamodb-local) and they started failing -- previous success was a week ago

Going back and using [amazon/dynamodb-local:2.1.0](https://hub.docker.com/layers/amazon/dynamodb-local/2.1.0/images/sha256-26a474015455758d13f08461d9a72b005007ddaa0145297bed8341ee0d5b2139?context=explore) fixes the issue

Specifically my parallel scan starts returning 0 results.

I note that the [usage notes](https://web.archive.org/web/20230628213910/https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html) documentation indicates that parallel scan is not supported:

> Scan operations are performed sequentially. Parallel scans are not supported. The Segment and TotalSegments parameters of the Scan operation are ignored.

But this warning has been present for a long time and these parameters are considered, and in the latest release a breaking change was introduced.

Apologies if this is not the right place to raise the issue but I can't find a better repository to report

**Comment by pasoevi** [comment]
Hi [tomwwright](https://github.com/tomwwright),

Thanks for reaching out. We have identified identified the change in functionality and will be releasing the version that matches the behavior from the usage notes you linked. We keep you posted once we release the version that addresses this.

**Comment by pasoevi** [comment]
Hi @tomwwright

You can update to version 2.2.1 which addresses the change in functionality.
