### ISSUE TITLE
DynamoDbLocal still has a dependency to org.eclipse.jetty.toolchain » jetty-jakarta-servlet-api:5.0.2. Update to 6.0

### ISSUE THREAD

**Issue by freyliis** [awslabs/amazon-dynamodb-local-samples#16]
DynamoDBLocal (as of version 2.3.0) still has **Servlet API 5.0** (coming in org.eclipse.jetty.toolchain.jetty-jakarta-servlet-api) and Spring Boot 3 / Tomcat 10 / Jetty 12 is based on **Servlet API 6.0** (coming in jakarta.servlet-api).

This may cause incompatibility issues, please update Servlet API to 6.0.

**Comment by shetsa-amzn** [comment]
We appreciate your feedback and we are currently reviewing this. We will update as soon as we have more information about next steps.

**Comment by shetsa-amzn** [comment]
This dependency was removed in the latest version(2.4.0) of DynamoDB Local

```
       <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>DynamoDBLocal</artifactId>
            <version>2.4.0</version>
        </dependency>
```
