### ISSUE TITLE
DynamoDB Local has jetty version incompatible with upcoming Spring Boot 3.2 jetty version

### ISSUE THREAD

**Issue by artur1211** [awslabs/amazon-dynamodb-local-samples#4]
There is an incompatibility between jetty versions in the upcoming Spring Boot 3.2 (it brings 12.0.1 jetty with it) and DynamoDB Local 2.0.0 (contains jetty in version 11.0.15). When one tries to run DynamoDB Local on the jetty (12.0.1) taken from Spring Boot 3.2 it leads to the following exception:
```
java.lang.IllegalAccessError: class com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer tried to access protected method 'void org.eclipse.jetty.server.Handler$AbstractContainer.<init>()' (com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer and org.eclipse.jetty.server.Handler$AbstractContainer are in unnamed module of loader 'app')
	at com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer.setUpHandler(DynamoDBProxyServer.java:50)
	at com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer.<init>(DynamoDBProxyServer.java:37)
        at...
```

It would be great if you could update Jetty to 12.0.1 (Spring Boot 3.2 version)

**Comment by shetsa-amzn** [comment]
We appreciate your feedback and we are currently reviewing this. We will update as soon as we have more information about next steps.

**Comment by dominic-miglar** [comment]
Same problem again:

https://github.com/awslabs/amazon-dynamodb-local-samples/issues/4

**Comment by ssanganbatte** [comment]
Hi, I am also facing the same issue. When can we expect the fix!!

**Comment by marat-aukhadiev-andsafe** [comment]
Any progress on the issue?
Is there a workaround?

**Comment by ssanganbatte** [comment]
I have updated my pom.xml to include the 11.x.x version instead of 12.x.x and scope to test. As I was using only for local testing and it worked for me. 

<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-server</artifactId>
    <version>11.0.18</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-util</artifactId>
    <version>11.0.18</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-io</artifactId>
    <version>11.0.18</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-http</artifactId>
    <version>11.0.18</version>
    <scope>test</scope>
</dependency>

**Comment by shetsa-amzn** [comment]
Hi, we currently have this planned in our issues backlog. We do not have an ETA, but it is being prioritized. We will provide a status update once this is in progress.

**Comment by harrydhillon43** [comment]
Facing the same issue as well

**Comment by klach-ocado** [comment]
> Is there a workaround?

An alternative way to obtain a mock client that does not use HTTP connections at all (so methods like `com.amazonaws.AmazonWebServiceResult#getSdkHttpMetadata` return `null`):
```
AmazonDynamoDB amazonDynamoDB = DynamoDBEmbedded.create().amazonDynamoDB();
```

**Comment by psiman-wandera** [comment]
Hi, we are facing the same issue. Any ETA of the fix would help a lot. Thanks!

**Comment by chris-tuncap** [comment]
Same here. We had to upgrade our Spring Boot to 2.2+ to resolve a vulnerability and we encountered this. Any idea when this will be worked? :)

**Comment by shetsa-amzn** [comment]
Hello Customers,

@artur1211 @ssanganbatte @marat-aukhadiev-andsafe @harrydhillon43 @klach-ocado @psiman-wandera @esagardia @chris-tuncap 

The DynamoDB DevEx team is continuously making improvements to DynamoDB local. As we have received feedback from you as a user of DynamoDB local as a Maven dependency. Our latest improvement to DynamoDB local is an upgrade to Jetty 12 to be compatible with Spring Boot 3.2.0. We are reaching out to you to see if you would like to participate in the early testing of our DynamoDB local beta version, which includes this upgrade. We would really appreciate your support as your participation will help us ensure high quality user experience with this upgrade before we launch to the general public.

If you would like to participate in early testing of our DynamoDB local beta release, please send us an email at: [aws-ddblocal-feedback@amazon.com](mailto:aws-ddblocal-feedback@amazon.com).

Regards,
The DynamoDB DevEx Team

**Comment by shetsa-amzn** [comment]
Today, we are excited to announce that DynamoDB local for [Amazon DynamoDB](https://aws.amazon.com/dynamodb/) upgrades to Jetty 12 and JDK 17. We recommend that you run the latest version (2.3.0) of DynamoDB local to utilize the most recent updates and features of DynamoDB local for your development and testing use cases.

https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-dynamodb-local-upgrades-jetty-12-jdk-17/

**Comment by psiman-wandera** [comment]
@shetsa-amzn thanks for quick fix of this issue 👏 

> Today, we are excited to announce that DynamoDB local for [Amazon DynamoDB](https://aws.amazon.com/dynamodb/) upgrades to Jetty 12 and JDK 17. We recommend that you run the latest version (2.3.0) of DynamoDB local to utilize the most recent updates and features of DynamoDB local for your development and testing use cases.
> 
> https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-dynamodb-local-upgrades-jetty-12-jdk-17/
